// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerCommissions.Users.Infrastructure;

#nullable disable

namespace PartnerCommissions.Users.Api.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCommissions.Users.Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InviterId")
                        .HasColumnType("uuid");

                    b.HasKey("ExternalId");

                    b.HasIndex("InviterId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Users.Infrastructure.Models.InviterTreeRow", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid?>("InviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_id");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Users.Infrastructure.Models.User", b =>
                {
                    b.HasOne("PartnerCommissions.Users.Infrastructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
