// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerCommissions.Commissions.Infrastructure;

#nullable disable

namespace PartnerCommissions.Commissions.Api.Infrastructure.Migrations
{
    [DbContext(typeof(CommissionsDbContext))]
    partial class CommissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCommissions.Commissions.Infrastructure.Models.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("AvailableAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartnerExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvailableAfter", "Id")
                        .HasFilter("\"PaidAt\" IS NULL");

                    b.HasIndex("EventId", "PartnerExternalId")
                        .IsUnique();

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Commissions.Infrastructure.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerExternalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("OwnerExternalId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Commissions.Infrastructure.Models.SchemaSetting", b =>
                {
                    b.Property<string>("SchemaType")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("SchemaType");

                    b.HasIndex("Enabled")
                        .IsUnique()
                        .HasFilter("\"Enabled\"");

                    b.ToTable("schema_settings", (string)null);

                    b.HasData(
                        new
                        {
                            SchemaType = "Linear",
                            Enabled = true
                        },
                        new
                        {
                            SchemaType = "Fibonacci",
                            Enabled = false
                        });
                });

            modelBuilder.Entity("PartnerCommissions.Commissions.Infrastructure.Models.Commission", b =>
                {
                    b.HasOne("PartnerCommissions.Commissions.Infrastructure.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
