// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerCommissions.Wallets.Infrastructure;

#nullable disable

namespace PartnerCommissions.Wallets.Api.Infrastructure.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    [Migration("20260917195426_InitialWallets")]
    partial class InitialWallets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCommissions.Wallets.Infrastructure.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AvailableAfter")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("CommissionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailableAfter", "Id")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Wallets.Infrastructure.Models.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartnerExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommissionId")
                        .IsUnique();

                    b.HasIndex("PartnerExternalId", "CreatedAt");

                    b.ToTable("payouts", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Wallets.Infrastructure.Models.Wallet", b =>
                {
                    b.Property<Guid>("PartnerExternalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("PartnerExternalId");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("PartnerCommissions.Wallets.Infrastructure.Models.Payout", b =>
                {
                    b.HasOne("PartnerCommissions.Wallets.Infrastructure.Models.Wallet", null)
                        .WithMany()
                        .HasForeignKey("PartnerExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
